cloud:
  aws:
    s3:
      bucket: ${CLOUD_AWS_S3_BUCKET:gochuchamchi-images}
    region:
      static: ${CLOUD_AWS_REGION_STATIC:ap-northeast-2}
spring:
  datasource:
    url: jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3306}/gochuchamchi?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${DB_USER:root}
    password: ${DB_PASS:}
    driver-class-name: org.mariadb.jdbc.Driver
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
  session:
    store-type: redis
    redis:
      namespace: gochuchamchi:session
    timeout: 3600
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    encoding: UTF-8
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.gochuchamchi.dto
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true
    session:
      timeout: 3600
logging:
  level:
    com.gochuchamchi: DEBUG
    org.mybatis: DEBUG
